server:
    port: 8089
spring:
  datasource:
      #type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/dbgril?useUnicode=true&characterEncoding=utf8&useSSL=true
      username: root
      password: root
  devtools:
    restart:
      enabled: true
 # data:
  #  mongodb:
   #   uri: mongodb://localhost:27017/test
mybatis: 
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: mybatis/**/*Mapper.xml

